# version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - scylla
    environment:
      - BOARD_SIZE=${BOARD_SIZE}
      - CLIENT_ID=${CLIENT_ID}
      - CALLBACK_URL=${CALLBACK_URL}
      - SCYLLA_KEYSPACE=${SCYLLA_KEYSPACE}
      - SCYLLA_CONTACT_POINTS=${SCYLLA_CONTACT_POINTS}
      - SCYLLA_DATACENTER=${SCYLLA_DATACENTER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PORT=${PORT}
      - COOLDOWN_PERIOD=${COOLDOWN_PERIOD}
    networks:
      - app-network

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - '9042:9042'
    volumes:
      - scylla-data:/var/lib/scylla
    environment:
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  scylla-data:
  redis-data:

networks:
  app-network:
    driver: bridge
