# version: '3.8'

services:
  app:
    build: .
    ports:
      - '1945:1945'
    depends_on:
      - redis
      - init-scylla
    networks:
      - app-network

  init-scylla:
    image: scylladb/scylla:latest
    entrypoint: ['cqlsh', 'scylla', '-e', "SOURCE '/init-scylla.cql'"]

    depends_on:
      scylla:
        condition: service_healthy
    volumes:
      - ./init-scylla.cql:/init-scylla.cql
    networks:
      - app-network

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - '9042:9042'
    volumes:
      - scylla-data:/var/lib/scylla
    environment:
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'cqlsh', '-e', 'DESCRIBE KEYSPACES']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  scylla-data:
  redis-data:

networks:
  app-network:
    driver: bridge
