# version: '3.8'

services:
  app:
    build: .
    ports:
      - '1945:1945'
    depends_on:
      - redis
      - scylla
    networks:
      - app-network

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - '9042:9042'
    volumes:
      - scylla-data:/var/lib/scylla
    environment:
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redus
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  scylla-data:
  redis-data:

networks:
  app-network:
    driver: bridge
